id: PB67957CD
initial_creation_type: input
source_metadata:
  title: Aspiration Prayers
  language: fr
  description: 'A series of prayers of aspiration (Skt. praṇidhāna; Tib. smon lam)
    and works from related genres, including prayers for the spread of the teachings
    (bstan rgyas smon lam):'
  volume:
    bcaf918a6e7c458eb1dde849c914e77f:
      title: 'Fostering Recollection to Dispel the Torment of Deluded Perception:
        An Aspiration for the Bardos'
      parent: Bardos
    d7a6b8f24c8c4d47bfcdf902b3f9e05c:
      title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
      parent: Bardos
    2f6690ab901d459f9e39b66751cea819:
      title: Maitreya's Aspiration
      parent: Bodhisattva Aspirations
    e9880de109b947838bfcf60ff20e3b82:
      title: 'The Blissful Path to the Ocean of Bodhichitta: A Brief Prayer of Aspiration
        for Mind Training'
      parent: Bodhisattva Aspirations
    1048f3360dfa4052a7a4b4d27c4280cc:
      title: 'The Excellent Path to Enlightenment: An Aspiration Towards the Mahāyāna
        Mind Training'
      parent: Bodhisattva Aspirations
    bbbd034133904e8690f99392f0cb3ddc:
      title: 'The Heart of the Mahāyāna Path: A Bodhisattva’s Prayer of Aspiration'
      parent: Bodhisattva Aspirations
    69c69422db7a41e490fbc710c32992cc:
      title: 'The Finest Jewel: An Aspiration Prayer of Mahāyāna Mind Training'
      parent: Bodhisattva Aspirations
    6d71dc555c2b474abe86ad93bb511f97:
      title: Prayer of Aspiration Incorporating the Eight Thoughts of Great Beings
        Who Follow the Way of the Mahāyāna
      parent: Bodhisattva Aspirations
    28527e93485d4876a221cccd8bfbdb71:
      title: Bodhicitta Aspiration
      parent: Bodhisattva Aspirations
    6564d7aa058d4a8db5d15595187ede61:
      title: Aspiration to Generate Bodhicitta, Utterly Pure and Supreme
      parent: Bodhisattva Aspirations
    6ea4c8ce21724f558632142a248a2dd5:
      title: The Way to Explain the King of All Aspiration Prayers, the Secret Vajra
        Knot
      parent: Commentaries
    b34a146128f24387897549170b64a7fb:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Copper-Coloured Mountain
    5404363b48e74276a06e66efa81063be:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Copper-Coloured Mountain
    19b6ec3699ad40c391ec5d5e966d663f:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Copper-Coloured Mountain
    b2044d616f33416dbb1b522c1b903c3e:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Copper-Coloured Mountain
    1c0bf5a08cf04f518133b521c308876f:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Copper-Coloured Mountain
    fb1a3c433bed4e39b4eeefa0e8e2a44a:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Copper-Coloured Mountain
    eba90659f4d74e22b027e72449829cf8:
      title: 'The Song of Devotion: Verses of Aspiration for the Fulfilment of the
        Enlightened Vision of Khenchen Jigme Phuntsok, the Reincarnation of Terton
        Lerab Lingpa'
      parent: Devotion
    d229cb68c9e449c38a02497197809536:
      title: An Aspiration
      parent: Dzogchen
    817ce9c126f948e28fefdfef179a2949:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Dzogchen
    0c7caeb60b5f4afb9d236b6d7021b5c4:
      title: 'Self-Radiance of Indestructible Awareness and Emptiness: An Aspiration
        towards the Meaning of the Indivisible Ground, Path and Fruition of the Great
        Perfection Mañjuśrī'
      parent: Dzogchen
    6474472a08ba48128fcecb4fed1fce11:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Dzogchen
    1ccc333c908940efa0a9878da29762f7:
      title: Prayer of the View, Meditation and Conduct
      parent: Dzogchen
    7c9ff2d35a514d898f02b42ad9ccdf86:
      title: Profound Prayer of Aspiration
      parent: Dzogchen
    1a14b93a37e24ac8b5571de2dd097a5c:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: General
    0f46844234314e16b0d69c8af727a000:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: General
    ee0943af85a943c6a404a027f737d914:
      title: 'The Vidyādharas'' Words of Truth: An Aspiration Connected with the Stages
        of the Path of the Three Roots, from the Heart Essence of the Vast Expanse'
      parent: General
    6d7ac4e879c447919cdf37c9fef6d02b:
      title: 'Wisdom''s Melody: An Aspiration to Realize Madhyamaka, Mahāmudrā, and
        Mahā Ati'
      parent: General
    57d58958673348c899033cdd079251d6:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: General
    8075341b2b1f4b54b679b1776f9ebb0b:
      title: Aspirations in Accordance with the Dharma
      parent: General
    c91e1cda2a634a69b945a1d362a09297:
      title: Aspiration at the Moment of Death
      parent: General
    e95b1f4e6abe4847bd2b1a17a11bdf57:
      title: Aspiration Prayer of the Ultimate Definitive Meaning
      parent: General
    d929d83a3a2f43a9a43ef883458ffcc7:
      title: An Aspiration Prayer
      parent: General
    1d1a1f785ec844709752a779b6114c79:
      title: Aspiration for All Lives to Come
      parent: General
    8ad3308d690347b4a4d34735f1bdc8c9:
      title: Aspiration Written in Sadness During the Water Snake Year
      parent: General
    ef69a6f65fdb4485aa114d4a2ace3e4b:
      title: Aspiration Written on the Occasion of Princess Sangdé’s Passing in Sikkim
      parent: General
    42789cd078494db398735f4f9100761c:
      title: Aspiration to Accomplish Every Aim
      parent: General
    2df69322848440c9bf123031bc3a1bfb:
      title: Aspiration to Be Reborn at the Vajra Seat (Bodhgayā), Akaniṣṭha on Earth
      parent: General
    c1282294b0464e50908c8d51d0403a5e:
      title: Prayer of Aspiration
      parent: General
    cd3aa8ee93784a5fb502fd1450791968:
      title: 'The Jewelled Rosary: An Aspiration Toward Longed-for Aims'
      parent: General
    2344149a2c284e7c93d58a19850364a6:
      title: 'The Swift Fulfilment of Wishes: A Prayer of Aspiration'
      parent: General
    02f7601235de487b8ff72f778decaa48:
      title: An Aspiration for the Final Age
      parent: General
    7146823d17024f91b7385db1593efc03:
      title: 'Entering the City of Omniscience: An Aspiration Prayer for Actualizing
        Words of Truth'
      parent: General
    68cfeef9e0424b0da0590175307f514e:
      title: Aspiration for Future Lives
      parent: General
    5ad1558ac5a1415ea8fde0f86751ef88:
      title: Aspiration to be Cared For in Every Lifetime
      parent: General
    afde84a66dbf435780ceccf637716bce:
      title: 'The Sun of Samantabhadra’s Realm: The Quintessence of Oceanic Prayers
        of Aspiration'
      parent: General
    aa2aae6c697a42ed9fcb17a6dbf4884e:
      title: An Aspiration to Travel to the Hidden Land of Pemokö
      parent: General
    547e1d8a70cf4b9d94d30007965cea81:
      title: 'The Magical Lasso: A Prayer of Aspiration to Accomplish Khecara'
      parent: General
    77763f4ce81341d8acd6bab7065caba0:
      title: The Secret Vajra Knot
      parent: General
    547fa32e0b7b44ba8890ec76711b5c7a:
      title: Aspiration for the Four Activities
      parent: General
    cc719f8cb50d440b9d11e7d7b5cc5136:
      title: The Source of Beings' Happiness
      parent: General
    3a7f9aeebbec4dbba9a46b64fd08a4dc:
      title: The Thirty Aspirations
      parent: General
    bf1ee98026874974ba9f8174f679ce91:
      title: Yeshe Tsogyal's Prayer
      parent: General
    1a28876b018b445ea455bbcdeeced343:
      title: Aspiration Prayer from Tārā Sādhana
      parent: General
    0d4cac6ec60b4386aafd4988e3ace5b6:
      title: Verses of Aspiration to Recite While Prostrating
      parent: General
    53cf5311708d457288b0e356d824cf8b:
      title: A Prayer of Aspiration
      parent: General
    3833ddb28d4544dda88c9ca62e8d36d6:
      title: Aspiration Prayer
      parent: General
    3f1fcac89edf40ecb51613136ca6d4be:
      title: Aspiration for the Stages of the Path
      parent: Lamrim
    911362e58c0b431490af439638ceb39b:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Longevity
    3dfa16573da34211af51d88d0f72552d:
      title: Concise Middle Way Aspiration
      parent: Madhyamaka
    28e64775445247e6820b6ab812979e41:
      title: Middle Way Aspiration
      parent: Madhyamaka
    701f91708b334d0dbbcb77da1b4428d4:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Mahāmudrā
    585e3ce60b8845fd9adc6185fc8c8baa:
      title: 'The Rishi''s Maledictory Incantation: An Invocation of Wisdom Mind and
        Sacred Pledges for Reversing the Disturbances and Agitations of Dark Times
        In the Form of an Aspiration Prayer'
      parent: Peace and Welfare
    111bf9113f6f4c40a2576a34adcb00d0:
      title: Aspiration for the Country’s Welfare
      parent: Peace and Welfare
    463c1ac69bf342629ba2f475386c773a:
      title: The Prayer of the Words of Truth
      parent: Peace and Welfare
    6f00c54393e344e2ba65ff0da679d300:
      title: 'The Resounding Drum of Truth: A Prayer and Aspiration'
      parent: Peace and Welfare
    b34af6a069b64fac9664da4129275a71:
      title: Prayer for Peace and Stability in Tibet
      parent: Peace and Welfare
    553dfbcc8fce45d09be7b2bd9bb77679:
      title: 'Burgeoning Joy and Happiness: An Aspiration for the Welfare of the Great
        Hidden Land of Sikkim'
      parent: Peace and Welfare
    1820992cc419432abfb9b2657c74407e:
      title: 'Declaration of the Power of Truth: A Prayer to Overcome Invading Forces'
      parent: Peace and Welfare
    930d6fbee2d9465a822739f3a30be1a4:
      title: 'The Fulfilment of All Aims and Wishes: An Aspiration to Request the
        Safeguarding of Happiness in Tibet'
      parent: Peace and Welfare
    6162515a5846489a8d49af846aaf715f:
      title: Prayer for Dispelling Famine
      parent: Peace and Welfare
    a492b2879d5c4a61b87f5221bc41cde2:
      title: Prayer of Truthful Words to Pacify the Fear of War
      parent: Peace and Welfare
    f795186283254b0ab32a87ec6cb7cf0a:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Peace and Welfare
    5fc10d01cc14429c88418ea7573feed9:
      title: 'The Jewelled Garland: An Aspiration for the Spread of the Teachings
        of the Omniscient Father and Son, Masters of the Teachings of the Ancient
        Translations'
      parent: Prayers for the Spread of the Teachings
    4080fc34f0bb498281da13bf95923490:
      title: Prayer for the Future of the Dharma
      parent: Prayers for the Spread of the Teachings
    bccd4763e5e0497db63de13dd5a9c41c:
      title: Aspiration Prayer for the Flourishing of the Jonang Teachings
      parent: Prayers for the Spread of the Teachings
    71f9bdb0ba0843d89d614fa296169508:
      title: 'The Sage''s Harmonious Song of Truth: A Prayer for the Flourishing of
        the Non-Sectarian Teachings of the Buddha'
      parent: Prayers for the Spread of the Teachings
    7cc7ee38522e4043b784ad7a53e84ea5:
      title: 'All-Pervading Auspiciousness: An Aspiration for the Spread of the Teachings
        of the Eight Great Chariots of the Practice Lineage'
      parent: Prayers for the Spread of the Teachings
    ef3edf8942434a15b1ba58b0de098488:
      title: Aspiration for the Spread of the Guhyagarbha Teachings
      parent: Prayers for the Spread of the Teachings
    fe7e74cfdcd54e62a4f9f0f048399c52:
      title: Aspiration for the Spread of the Teachings
      parent: Prayers for the Spread of the Teachings
    20780b9634984d36b5b07e6bc6f2a081:
      title: 'Blazing Splendour of Good Fortune: A Prayer for the Spread of the Teachings
        of the Katok Tradition'
      parent: Prayers for the Spread of the Teachings
    808081cb44ed48d3baf0827b378c3942:
      title: 'Introduction to the Buddha’s Words: A Praise and Aspiration Related
        to the Words of the Victorious One'
      parent: Prayers for the Spread of the Teachings
    b95e93dce01546c3b47946ce15e88908:
      title: 'The Sage''s Powerful Words of Truth: A Prayer for the Spread of the
        Omniscient Buddha''s Teachings'
      parent: Prayers for the Spread of the Teachings
    53af0fd389464342af620d54c53c0cd6:
      title: The Last Testament of Katok Dampa Deshek
      parent: Prayers for the Spread of the Teachings
    d4971e2ccfc34689a1fe2f9c5b45c1ca:
      title: Prayer of Aspiration for the Buddhist Teachings to Flourish in Taiwan
      parent: Prayers for the Spread of the Teachings
    5a1c92c0a0d04db09a1075edb85e801d:
      title: Aspiration for the Spread of the Teachings of the Eight Chariots of the
        Practice Lineage
      parent: Prayers for the Spread of the Teachings
    6c7118e7a0fe4d978530d40d45a6a2d3:
      title: Clouds of Offerings to Delight the Victorious Ones – An Aspiration Prayer
        for the Spread of the Teachings of the Lord of Siddhas, Dzogchen Rinpoche
      parent: Prayers for the Spread of the Teachings
    d7b64cccb2874b4b8e5e4157b069ce30:
      title: 'Words of Truth: An Aspiration for the Spread of the Noble Gendenpa Tradition'
      parent: Prayers for the Spread of the Teachings
    5d3580be05884593ac20a743a64f7569:
      title: 'Words to Delight the Sovereigns of the Dharma: A Prayer of Aspiration
        for the Flourishing and Spread of the Ancient Translation Tradition'
      parent: Prayers for the Spread of the Teachings
    6fa3a305710a418fb10577b5e91d76ab:
      title: Prayer for the Flourishing of the Teachings
      parent: Prayers for the Spread of the Teachings
    8876da29145e4d1ba49a8b696ff170ac:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Prayers for the Spread of the Teachings
    bbba2692ae0144c3b9ec1e572ac45945:
      title: Prayer for the Flourishing of the Dzogchen Teachings of Sogyal Rinpoche,
        the incarnation of Lerab Lingpa
      parent: Prayers for the Spread of the Teachings
    dd19283fd40e4f21a132308f5047639e:
      title: A Brief Method for Reciting Samantabhadra's Prayer of Good Actions
      parent: Recitation Guides
    65b44aa8ce3d4ce3b3b767c7527f937b:
      title: A Prayer for Translators
      parent: Translation
    7c1f4c311afd4caf9088014f1d48b3fc:
      title: An Aspirational Prayer to Behold the Beautiful Face of Khecharī
      parent: Vajrayoginī
created_at: '2022-03-01T02:50:17.923800'
last_modified_at: '2022-03-01T02:50:17.923802'
